Repository YAPP-18th/Android-Team-1-Backend, pull requests merged in 2021-07, with the labels that each got.

#162 Fix: 사용자 기록 탭 답변 목록 정렬 순서 변경
  mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java
Labels: application, bug

#163 master 최신화
  mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java
Labels: application, bug

#167 Fix/member reply order
  deployment/deployment.yml
  mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java
Labels: application, bug

#168 마스터 최신화
  mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java
Labels: application, bug

#178 Fix: 머렝 쿠키 관련 뱃지 획득 조건 변경
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java
Labels: application, bug

#179 [기능] 머렝카운트에서 쿠키획득 엔티티로 변경
  mureng-api/src/main/java/net/mureng/api/member/component/MemberMapper.java
  mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java
  mureng-api/src/test/java/net/mureng/api/member/component/MemberMapperTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/TodayQuestionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/web/HomeControllerTest.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/cookie/entity/CookieAchievement.java
  mureng-core/src/main/java/net/mureng/core/cookie/repository/CookieAchievementRepository.java
  mureng-core/src/main/java/net/mureng/core/cookie/service/CookieAchievementService.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyPostProcessServiceImpl.java
  mureng-core/src/main/resources/config/liquibase/changelog/20210708_add_cookie_entity.xml
  mureng-core/src/main/resources/config/liquibase/changelog/20210708_drop_member_mureng_count.xml
  mureng-core/src/main/resources/config/liquibase/master.xml
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
  mureng-core/src/test/java/net/mureng/core/member/repository/MemberRepositoryTest.java
  mureng-core/src/test/java/net/mureng/core/reply/service/ReplyPostProcessServiceImplTest.java
  mureng-core/src/test/resources/dbunit/entity/member.xml
  mureng-core/src/test/resources/dbunit/expected/멤버_회원가입.xml
Labels: application, enhancement

#185 [수정] 쿠키 중복 획득 처리 해결
  mureng-core/src/main/java/net/mureng/core/cookie/repository/CookieAcquirementRepository.java
  mureng-core/src/main/java/net/mureng/core/cookie/service/CookieAcquirementService.java
  mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyPostProcessServiceImpl.java
  mureng-core/src/test/java/net/mureng/core/cookie/repository/CookieAcquirementRepositoryTest.java
  mureng-core/src/test/resources/dbunit/entity/cookie_acquirement.xml
Labels: application, bug

#187 Refactor: 오늘의 표현 가져오기 테이블 방식으로 변경, 배치 사용
  mureng-api/src/main/java/net/mureng/api/member/component/MemberScrapMapper.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberScrapDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberScrapController.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/dto/UsefulExpressionDto.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/web/TodayExpressionController.java
  mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java
  mureng-api/src/test/java/net/mureng/api/member/component/MemberScrapMapperTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/component/TodayExpressionMapperTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/component/UsefulExpressionMapperTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/web/UsefulExpressionControllerTest.java
  mureng-batch/src/main/java/net/mureng/batch/push/job/FcmDailyPushJobConfig.java
  mureng-batch/src/main/java/net/mureng/batch/question/job/TodayQuestionRefreshJobConfig.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/job/TodayExpressionMaintainJobConfig.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/job/TodayExpressionMaintainJobRequestService.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/job/TodayExpressionMaintainQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/service/TodayUsefulExpressionMaintainService.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/service/TodayUsefulExpressionMaintainServiceImpl.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/job/TodayExpressionRefreshJobConfig.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/job/TodayExpressionRefreshJobRequestService.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/job/TodayExpressionRefreshQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/service/TodayUsefulExpressionRefreshService.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/service/TodayUsefulExpressionRefreshServiceImpl.java
  mureng-batch/src/main/java/net/mureng/batch/util/CronExpression.java
  mureng-batch/src/test/java/net/mureng/batch/todayexpression/refresh/service/TodayUsefulExpressionRefreshServiceTest.java
  mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java
  mureng-core/src/main/java/net/mureng/core/member/entity/MemberScrap.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/entity/TodayUsefulExpression.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/entity/UsefulExpression.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/repository/TodayExpressionRepository.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/repository/TodayUsefulExpressionRepository.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/repository/UsefulExpressionRepository.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/service/UsefulExpressionService.java
  mureng-core/src/main/resources/config/liquibase/changelog/20210708_today_expression.xml
  mureng-core/src/main/resources/config/liquibase/master.xml
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
  mureng-core/src/test/java/net/mureng/core/member/repository/MemberScrapRepositoryTest.java
  mureng-core/src/test/resources/dbunit/entity/useful_expression.xml
  mureng-core/src/test/resources/sql/integration.sql
Labels: application, enhancement

#190 feat: 요청 및 응답 로깅 추가, 로깅 레벨 조정
  mureng-api/src/main/java/net/mureng/api/core/component/RequestLogFilter.java
  mureng-core/src/main/resources/application.yml
Labels: application

#191 feat: 회원가입시 닉네임 검증 로직 추가
  mureng-api/src/main/java/net/mureng/api/core/util/NicknameNormalizer.java
  mureng-api/src/main/java/net/mureng/api/core/validation/KorEngOnlyValidator.java
  mureng-api/src/main/java/net/mureng/api/core/validation/annotation/KorEngOnly.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java
  mureng-api/src/test/java/net/mureng/api/core/util/NicknameNormalizerTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/AbstractValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/DateStringValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/KorEngOnlyValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/TimeStringValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/question/component/QuestionDtoValidationTest.java
Labels: application

#192 test: 통합 테스트 작성
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberAchievementDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberBadgeService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberAchievementController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberBadgeController.java
  mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberAchievementControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberBadgeControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberScrapControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/QuestionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/QuestionReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/TodayQuestionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyLikesControllerTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/web/UsefulExpressionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/web/AbstractControllerTest.java
  mureng-core/src/test/resources/sql/integration.sql
Labels: Test, application

#196 [정기배포] 1.0.1-RELEASE
  mureng-api/src/main/java/net/mureng/api/MurengApiApplication.java
  mureng-api/src/main/java/net/mureng/api/core/component/RequestLogFilter.java
  mureng-api/src/main/java/net/mureng/api/core/util/NicknameNormalizer.java
  mureng-api/src/main/java/net/mureng/api/core/validation/KorEngOnlyValidator.java
  mureng-api/src/main/java/net/mureng/api/core/validation/annotation/KorEngOnly.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberAchievementDto.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberBadgeService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberAchievementController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberBadgeController.java
  mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java
  mureng-api/src/test/java/net/mureng/api/core/util/NicknameNormalizerTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/AbstractValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/DateStringValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/KorEngOnlyValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/core/validation/TimeStringValidatorTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberAchievementControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberBadgeControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberScrapControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/component/QuestionDtoValidationTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/QuestionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/QuestionReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/web/TodayQuestionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyLikesControllerTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/web/UsefulExpressionControllerTest.java
  mureng-api/src/test/java/net/mureng/api/web/AbstractControllerTest.java
  mureng-batch/src/main/java/net/mureng/batch/push/service/FcmDailyPushService.java
  mureng-batch/src/test/java/net/mureng/batch/AbstractJobTest.java
  mureng-batch/src/test/java/net/mureng/batch/push/job/FcmDailyPushJobTest.java
  mureng-batch/src/test/java/net/mureng/batch/question/job/TodayQuestionRefreshJobTest.java
  mureng-core/src/main/resources/application.yml
  mureng-core/src/main/resources/config/liquibase/changelog/00000000_initial_schema.xml
  mureng-core/src/test/resources/sql/integration.sql
Labels: application

#195 [리팩토링] 엔티티 매퍼 수정
  mureng-api/src/main/java/net/mureng/api/core/component/EntityMapper.java
  mureng-api/src/main/java/net/mureng/api/member/component/MemberAchievementMapper.java
  mureng-api/src/main/java/net/mureng/api/member/component/MemberMapper.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberAchievementDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberBadgeService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberAchievementController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberBadgeController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberScrapController.java
  mureng-api/src/main/java/net/mureng/api/question/component/QuestionMapper.java
  mureng-api/src/main/java/net/mureng/api/question/component/WordHintMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyLikesMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyController.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/dto/UsefulExpressionDto.java
  mureng-api/src/test/java/net/mureng/api/member/component/MemberAchievementMapperTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberAchievementControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberBadgeControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberScrapControllerTest.java
  mureng-api/src/test/java/net/mureng/api/question/component/QuestionMapperTest.java
  mureng-api/src/test/java/net/mureng/api/reply/component/ReplyMapperTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/component/UsefulExpressionMapperTest.java
  mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java
  mureng-core/src/main/java/net/mureng/core/core/message/ResponseMessage.java
Labels: application, help wanted, refactoring

#201 refactor: 배치 잡 등록 방식 변경
  build.gradle
  mureng-batch/src/main/java/net/mureng/batch/core/config/AbstractJobConfig.java
  mureng-batch/src/main/java/net/mureng/batch/core/config/AutowiringSpringBeanJobFactory.java
  mureng-batch/src/main/java/net/mureng/batch/core/config/BatchConfig.java
  mureng-batch/src/main/java/net/mureng/batch/core/config/QuartzConfig.java
  mureng-batch/src/main/java/net/mureng/batch/core/job/AbstractJobConductor.java
  mureng-batch/src/main/java/net/mureng/batch/core/job/MurengBatchJobService.java
  mureng-batch/src/main/java/net/mureng/batch/core/job/MurengJobLauncher.java
  mureng-batch/src/main/java/net/mureng/batch/core/job/MurengJobLauncherProvider.java
  mureng-batch/src/main/java/net/mureng/batch/core/job/MurengQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/core/job/ScheduledJobFactory.java
  mureng-batch/src/main/java/net/mureng/batch/core/trigger/CronTriggerProvider.java
  mureng-batch/src/main/java/net/mureng/batch/core/trigger/SimpleTriggerProvider.java
  mureng-batch/src/main/java/net/mureng/batch/core/trigger/TriggerProvider.java
  mureng-batch/src/main/java/net/mureng/batch/core/trigger/TriggerProviderFactory.java
  mureng-batch/src/main/java/net/mureng/batch/push/job/FcmDailyPushJobConductor.java
  mureng-batch/src/main/java/net/mureng/batch/push/job/FcmDailyPushJobRequestService.java
  mureng-batch/src/main/java/net/mureng/batch/push/job/FcmDailyPushQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/question/job/TodayQuestionRefreshJobConductor.java
  mureng-batch/src/main/java/net/mureng/batch/question/job/TodayQuestionRefreshJobRequestService.java
  mureng-batch/src/main/java/net/mureng/batch/question/job/TodayQuestionRefreshQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/job/TodayExpressionMaintainJobConductor.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/job/TodayExpressionMaintainJobRequestService.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/maintain/job/TodayExpressionMaintainQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/job/TodayExpressionRefreshJobConductor.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/job/TodayExpressionRefreshJobRequestService.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/job/TodayExpressionRefreshQuartzJob.java
  mureng-batch/src/main/java/net/mureng/batch/util/CronExpression.java
  mureng-batch/src/main/resources/application-localbatch.yml
  mureng-batch/src/main/resources/quartz_schema.sql
  mureng-batch/src/test/java/net/mureng/batch/push/job/FcmDailyPushJobTest.java
  mureng-batch/src/test/java/net/mureng/batch/question/job/TodayQuestionRefreshJobTest.java
Labels: application, refactoring

#202 [추가] 출석체크 로직 추가 및 관련 테스트 추가
  .github/workflows/gradle-test.yml
  .github/workflows/test-and-deploy-app-prod.yaml
  .github/workflows/test-and-deploy-batch-prod.yaml
  .github/workflows/test-and-deploy-dev.yaml
  build.gradle
  mureng-api/src/main/java/net/mureng/api/core/component/AttendanceCheckInterceptor.java
  mureng-api/src/main/java/net/mureng/api/core/config/HttpConfig.java
  mureng-api/src/main/java/net/mureng/api/core/config/SecurityConfig.java
  mureng-api/src/main/java/net/mureng/api/core/dto/UserDetailsImpl.java
  mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtAuthenticationFilter.java
  mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtResolver.java
  mureng-api/src/main/java/net/mureng/api/core/util/AuthenticationHelper.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberAuthControllerTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberControllerTest.java
  mureng-api/src/test/java/net/mureng/api/web/HomeControllerTest.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
Labels: application, feature

#205 Feature 199/exception
  mureng-api/src/main/java/net/mureng/api/core/advice/DefaultControllerAdvice.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberBadgeService.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java
  mureng-api/src/main/java/net/mureng/api/web/ProbeController.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyLikesControllerTest.java
  mureng-batch/src/main/java/net/mureng/batch/todayexpression/refresh/service/TodayUsefulExpressionRefreshServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeService.java
  mureng-core/src/main/java/net/mureng/core/core/exception/EntityNotFoundException.java
  mureng-core/src/main/java/net/mureng/core/core/exception/MurengException.java
  mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
Labels: application, refactoring
