Repository YAPP-18th/Android-Team-1-Backend, pull requests merged in 2021-06, with the labels that each got.

#131 [수정] 사용자 식별을 email에서 identifier로 변경
  mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtCreator.java
  mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtResolver.java
  mureng-api/src/main/java/net/mureng/api/core/jwt/service/JwtService.java
  mureng-api/src/main/java/net/mureng/api/core/jwt/web/JwtController.java
  mureng-api/src/main/java/net/mureng/api/core/oauth2/dto/OAuth2Profile.java
  mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/UserDetailsServiceImpl.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/test/java/net/mureng/api/jwt/JwtAuthenticationTest.java
  mureng-api/src/test/java/net/mureng/api/oauth/OAuthTest.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
  mureng-core/src/main/java/net/mureng/core/member/repository/MemberRepository.java
  mureng-core/src/main/java/net/mureng/core/member/service/MemberService.java
Labels: application, enhancement, urgent

#133 [기능] 뱃지 획득
  mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java
  mureng-core/src/main/java/net/mureng/core/badge/repository/BadgeAccomplishedRepository.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedService.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeService.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
Labels: feature

#137 Fix: 사용자 프로필 얻어오기 yml 정보 수정
  mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java
  mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
  mureng-core/src/main/resources/application.yml
Labels: application, bug

#139 Add: 프론트 요청으로 push 관련 엔드포인트 추가
  mureng-api/src/main/java/net/mureng/api/core/config/SecurityConfig.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberSettingController.java
  mureng-api/src/main/java/net/mureng/api/web/ProbeController.java
Labels: application, feature

#142 Add: FcmToken 관련 엔드포인트 관리, 비로그인 사용자 fcm 토큰추가할 수 있도록 변경
  mureng-api/src/main/java/net/mureng/api/core/config/SecurityConfig.java
  mureng-api/src/main/java/net/mureng/api/member/component/MemberMapper.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/main/java/net/mureng/api/web/FcmTokenController.java
  mureng-api/src/test/java/net/mureng/api/web/FcmTokenControllerTest.java
  mureng-batch/src/main/java/net/mureng/batch/push/job/FcmDailyPushJobConfig.java
  mureng-batch/src/main/java/net/mureng/batch/push/service/FcmDailyPushService.java
  mureng-core/src/main/java/net/mureng/core/member/entity/FcmToken.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
  mureng-core/src/main/java/net/mureng/core/member/repository/FcmTokenRepository.java
  mureng-core/src/main/java/net/mureng/core/member/service/FcmTokenService.java
  mureng-core/src/main/java/net/mureng/push/service/FcmLikePushServiceImpl.java
  mureng-core/src/main/resources/config/liquibase/changelog/20210619_fcm_token.xml
  mureng-core/src/main/resources/config/liquibase/master.xml
Labels: application, enhancement

#147 Add: 회원가입 탈퇴 로직 작성
  mureng-api/src/main/java/net/mureng/api/member/service/MemberSignupService.java
  mureng-api/src/main/java/net/mureng/api/member/service/UserDetailsServiceImpl.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
  mureng-core/src/main/java/net/mureng/core/member/repository/MemberRepository.java
  mureng-core/src/main/java/net/mureng/core/member/service/MemberService.java
  mureng-core/src/test/java/net/mureng/core/member/repository/MemberRepositoryTest.java
  mureng-core/src/test/resources/dbunit/entity/member.xml
  mureng-core/src/test/resources/dbunit/expected/멤버_머렝_카운트_증가.xml
Labels: application, feature

#148 [수정] Fcm Token 설정
  mureng-api/src/main/java/net/mureng/api/web/FcmTokenController.java
  mureng-core/src/main/java/net/mureng/core/member/repository/FcmTokenRepository.java
  mureng-core/src/main/java/net/mureng/core/member/service/FcmTokenService.java
  mureng-core/src/main/java/net/mureng/push/service/FcmLikePushServiceImpl.java
Labels: application, bug

#150 [기능] 뱃지 팝업 Response
  mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberScrapController.java
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyController.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberScrapControllerTest.java
  mureng-api/src/test/java/net/mureng/api/reply/component/ReplyMapperTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/component/TodayExpressionMapperTest.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/member/repository/MemberScrapRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/badge/repository/BadgeAccomplishedRepositoryTest.java
  mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
Labels: application

#158 [리팩토링] 서비스단 에러 메시지 및 PostProcess 버그 수정
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/badge/service/BadgeService.java
  mureng-core/src/main/java/net/mureng/core/core/component/DirectoryScanner.java
  mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java
  mureng-core/src/main/java/net/mureng/core/member/service/MemberService.java
  mureng-core/src/main/java/net/mureng/core/question/service/QuestionService.java
  mureng-core/src/main/java/net/mureng/core/question/service/TodayQuestionSelectionServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/question/service/TodayQuestionService.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyPostProcessServiceImpl.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java
  mureng-core/src/test/java/net/mureng/core/reply/service/ReplyPostProcessServiceImplTest.java
  mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
Labels: application, refactoring

#160 Fix: mapper null값 대신 0L으로 변경
  mureng-api/src/main/java/net/mureng/api/member/component/MemberAchievementMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java
Labels: application, bug
