Repository YAPP-18th/Android-Team-1-Backend, pull requests merged in 2021-05, with the labels that each got.

#47 [기능] 로그인 기능 및 JWT 리팩토링
  src/main/java/net/mureng/mureng/core/config/RestTemplateConfig.java
  src/main/java/net/mureng/mureng/core/config/Role.java
  src/main/java/net/mureng/mureng/core/config/SecurityConfig.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtAuthenticationFilter.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtCreator.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtResolver.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtValidator.java
  src/main/java/net/mureng/mureng/core/jwt/dto/TokenDto.java
  src/main/java/net/mureng/mureng/core/jwt/service/JwtService.java
  src/main/java/net/mureng/mureng/core/jwt/web/JwtController.java
  src/main/java/net/mureng/mureng/core/oauth2/dto/OAuth2Profile.java
  src/main/java/net/mureng/mureng/core/oauth2/service/OAuth2Service.java
  src/main/java/net/mureng/mureng/member/dto/MemberDto.java
  src/main/java/net/mureng/mureng/member/entity/Member.java
  src/main/java/net/mureng/mureng/member/repository/MemberRepository.java
  src/main/java/net/mureng/mureng/member/service/MemberService.java
  src/main/java/net/mureng/mureng/member/service/UserDetailsServiceImpl.java
  src/main/java/net/mureng/mureng/member/web/MemberController.java
  src/main/resources/application.properties
  src/test/java/net/mureng/mureng/jwt/JwtAuthenticationTest.java
  src/test/java/net/mureng/mureng/member/repository/MemberRepositoryTest.java
  src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java
  src/test/java/net/mureng/mureng/oauth/OAuthTest.java
  src/test/java/net/mureng/mureng/web/HomeControllerTest.java
Labels: Backend, JWT

#48 [기능] 답변 작성하기
  src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/entity/Reply.java
  src/main/java/net/mureng/mureng/reply/entity/ReplyLikes.java
  src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java
  src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
  src/test/resources/dbunit/entity/reply.xml
Labels: Backend, enhancement

#52 [기능] 답변 수정하기 및 삭제하기
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/entity/Reply.java
  src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java
  src/test/java/net/mureng/mureng/reply/service/ReplyServiceTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, enhancement

#55 [기능] 파일 업로드 구현 및 매니페스트 파일에 httpd 컨테이너 추가
  .github/workflows/test-and-deploy-dev.yaml
  .gitignore
  deployment/deployment-dev.yml
  src/main/java/net/mureng/mureng/core/component/FileUploader.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/main/resources/application.yml
  src/test/java/net/mureng/mureng/core/component/FileUploaderTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, enhancement

#58 [기능] swagger-ui 개편, JWT 인증 수단 추가
  src/main/java/net/mureng/mureng/core/annotation/CurrentUser.java
  src/main/java/net/mureng/mureng/core/config/SwaggerConfig.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtCreator.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtResolver.java
  src/main/java/net/mureng/mureng/core/jwt/component/JwtValidator.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
Labels: Backend, documentation, enhancement

#59 [기능, 보완] 회원가입 닉네임 중복체크, 회원가입 사후 처리 및 불필요한 회원 입력 파라미터 제거
  .gitignore
  src/main/java/net/mureng/mureng/core/config/SwaggerConfig.java
  src/main/java/net/mureng/mureng/member/component/MemberMapper.java
  src/main/java/net/mureng/mureng/member/dto/MemberDto.java
  src/main/java/net/mureng/mureng/member/service/MemberService.java
  src/main/java/net/mureng/mureng/member/service/MemberSignupService.java
  src/main/java/net/mureng/mureng/member/web/MemberController.java
  src/main/java/net/mureng/mureng/question/dto/QuestionDto.java
  src/main/java/net/mureng/mureng/question/dto/WordHintDto.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/test/java/net/mureng/mureng/member/component/MemberMapperTest.java
  src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java
Labels: Backend, enhancement, feature

#62 [기능] 질문 페이징 목록 조회
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/java/net/mureng/mureng/reply/service/ReplyServiceTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, feature

#67 [기능] 질문 조회하기
  src/main/java/net/mureng/mureng/question/component/QuestionMapper.java
  src/main/java/net/mureng/mureng/question/dto/QuestionDto.java
  src/main/java/net/mureng/mureng/question/entity/Question.java
  src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java
  src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/resources/dbunit/entity/question.xml
Labels: Backend, feature

#69 [기능] 질문 연관 답변 조회 추가
  src/main/java/net/mureng/mureng/core/dto/ApiPageRequest.java
  src/main/java/net/mureng/mureng/core/dto/ApiPageResult.java
  src/main/java/net/mureng/mureng/core/dto/ApiResult.java
  src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/entity/Reply.java
  src/main/java/net/mureng/mureng/reply/entity/ReplyLikes.java
  src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java
  src/test/resources/dbunit/entity/reply.xml
Labels: Backend, feature

#73 [기능] 기본 이미지 목록 받아오는 엔드포인트 추가
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/main/java/net/mureng/mureng/reply/web/ReplyImageController.java
Labels: Backend, feature

#74 [기능] 오늘의 질문 새로고침하는 엔드포인트 추가
  src/main/java/net/mureng/mureng/core/component/NumberRandomizer.java
  src/main/java/net/mureng/mureng/question/entity/TodayQuestion.java
  src/main/java/net/mureng/mureng/question/service/TodayQuestionSelectionService.java
  src/main/java/net/mureng/mureng/question/service/TodayQuestionSelectionServiceImpl.java
  src/main/java/net/mureng/mureng/question/service/TodayQuestionService.java
  src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java
  src/test/java/net/mureng/mureng/question/service/TodayQuestionSelectionServiceImplTest.java
  src/test/java/net/mureng/mureng/question/web/TodayQuestionControllerTest.java
Labels: Backend, feature

#71 [기능] 답변 목록 조회 추가
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, feature

#72 [보완] 객체 매핑 로직 modelmapper -> mapstruct으로 변경
  build.gradle
  src/main/java/net/mureng/mureng/core/component/EntityMapper.java
  src/main/java/net/mureng/mureng/member/component/MemberMapper.java
  src/main/java/net/mureng/mureng/member/dto/MemberDto.java
  src/main/java/net/mureng/mureng/member/web/MemberController.java
  src/main/java/net/mureng/mureng/question/component/QuestionMapper.java
  src/main/java/net/mureng/mureng/question/component/WordHintMapper.java
  src/main/java/net/mureng/mureng/question/dto/QuestionDto.java
  src/main/java/net/mureng/mureng/question/dto/WordHintDto.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/entity/Reply.java
  src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/member/component/MemberMapperTest.java
  src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java
  src/test/java/net/mureng/mureng/question/component/WordHintMapperTest.java
  src/test/java/net/mureng/mureng/reply/component/ReplyMapperTest.java
  src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java
  src/test/java/net/mureng/mureng/reply/service/ReplyServiceTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, enhancement

#76 [보완] 페이징 관련 엔드포인트 응답에 페이지 정보 추가
  src/main/java/net/mureng/mureng/core/dto/ApiPageResult.java
  src/main/java/net/mureng/mureng/core/dto/ApiResult.java
  src/main/java/net/mureng/mureng/member/dto/MemberDto.java
  src/main/java/net/mureng/mureng/question/dto/QuestionDto.java
  src/main/java/net/mureng/mureng/question/dto/WordHintDto.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, enhancement

#79 [기능] 질문에 대한 내 답변 가져오기 엔드포인트 추가
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/main/java/net/mureng/mureng/question/web/QuestionReplyController.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/java/net/mureng/mureng/question/web/QuestionReplyControllerTest.java
Labels: Backend, feature

#81 [기능] 사용자 답변 목록, 사용자 오늘 답변 유무 엔드포인트 추가
  src/main/java/net/mureng/mureng/member/web/MemberController.java
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java
  src/test/java/net/mureng/mureng/reply/component/ReplyMapperTest.java
Labels: Backend, feature

#82 [보완] 페이징에서 정렬 값 enum으로 변경
  src/main/java/net/mureng/mureng/core/dto/ApiPageRequest.java
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/main/java/net/mureng/mureng/question/web/QuestionReplyController.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/java/net/mureng/mureng/question/web/QuestionReplyControllerTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, enhancement

#83 [기능] ReplyDto 에 requestedByAuthor 필드 추가, 관련 매퍼 수정
  src/main/java/net/mureng/mureng/question/web/QuestionReplyController.java
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
  src/test/java/net/mureng/mureng/question/web/QuestionReplyControllerTest.java
  src/test/java/net/mureng/mureng/reply/component/ReplyMapperTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: Backend, feature

#84 [기능] 현재 로그인한 사용자 조회 엔드포인트 추가, 사용자 답변 컨트롤러 분리
  src/main/java/net/mureng/mureng/member/web/MemberController.java
  src/main/java/net/mureng/mureng/member/web/MemberReplyController.java
  src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java
  src/test/java/net/mureng/mureng/member/web/MemberReplyControllerTest.java
Labels: Backend, feature

#87 [기능] 질문 등록하기
  src/main/java/net/mureng/mureng/question/component/QuestionMapper.java
  src/main/java/net/mureng/mureng/question/entity/Question.java
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/question/web/QuestionController.java
  src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java
  src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
Labels: feature

#86 [기능] 답변 상세 조회
  src/main/java/net/mureng/mureng/member/web/MemberReplyController.java
  src/main/java/net/mureng/mureng/reply/service/ReplyService.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/member/web/MemberReplyControllerTest.java
  src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
Labels: enhancement, feature

#91 [기능] 사용자 프로필 정보 가져오기
  src/main/java/net/mureng/mureng/member/service/MemberService.java
  src/main/java/net/mureng/mureng/member/web/MemberController.java
  src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java
Labels: application, feature

#92 [보완] ReplyMapper 엔티티 변환 메서드 추가
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/web/ReplyController.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/reply/component/ReplyMapperTest.java
Labels: application, enhancement

#95 [기능] 질문 가져오기에서 작성자 정보 추가
  src/main/java/net/mureng/mureng/member/dto/MemberDto.java
  src/main/java/net/mureng/mureng/question/component/QuestionMapper.java
  src/main/java/net/mureng/mureng/question/dto/QuestionDto.java
  src/main/java/net/mureng/mureng/question/dto/WordHintDto.java
  src/main/java/net/mureng/mureng/question/entity/Question.java
  src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java
  src/main/java/net/mureng/mureng/question/service/QuestionService.java
  src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java
  src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java
  src/test/java/net/mureng/mureng/common/EntityCreator.java
  src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java
  src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java
  src/test/java/net/mureng/mureng/question/web/TodayQuestionControllerTest.java
Labels: application, feature

#96 [보완] github-action 캐싱 사용하여 배포 속도 향상
  .github/workflows/gradle-test.yml
  .github/workflows/test-and-deploy-dev.yaml
  Dockerfile
  deployment/deployment-dev.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, infrastructure

#100 [기능] 답변 좋아요
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyLikesMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyLikesDto.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyController.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyLikesController.java
  mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java
  mureng-api/src/test/java/net/mureng/api/reply/component/ReplyLikesMapperTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyLikesControllerTest.java
  mureng-core/src/main/java/net/mureng/core/reply/entity/ReplyLikesPK.java
  mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyLikesRepository.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
Labels: application, feature

#101 [보완] ReplyDto에 likedByMember 추가
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java
  mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java
  mureng-api/src/main/java/net/mureng/api/reply/service/ReplyImageService.java
  mureng-api/src/main/java/net/mureng/api/reply/service/ReplyPaginationService.java
  mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java
  mureng-api/src/test/java/net/mureng/api/reply/component/ReplyMapperTest.java
  mureng-core/src/main/java/net/mureng/core/reply/entity/Reply.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
Labels: application, enhancement

#102 [보완] PageResult 전체 요소 개수 추가
  mureng-api/src/main/java/net/mureng/api/core/dto/ApiPageResult.java
  mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java
  mureng-core/src/test/resources/dbunit/entity/reply.xml
Labels: application, enhancement, request

#105 [수정] 파드로부터 아파치 컨테이너 별도의 파드로 분리
  deployment/deployment-dev.yml
Labels: enhancement, infrastructure

#106 [기능] 오늘의 표현 가져오기
  mureng-api/src/main/java/net/mureng/api/reply/component/ReplyLikesMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/web/TodayExpressionController.java
  mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/component/TodayExpressionMapperTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/web/TodayExpressionControllerTest.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/entity/TodayExpression.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
Labels: application, feature

#111 [기능] 기본 이미지 목록 더미 제거, 실제 디렉토리 스캔으로 변경
  mureng-api/src/main/java/net/mureng/api/reply/service/ReplyImageService.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyImageController.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java
  mureng-api/src/test/java/net/mureng/api/reply/web/ReplyImageControllerTest.java
  mureng-core/src/main/java/net/mureng/core/core/component/DirectoryScanner.java
Labels: application, feature

#112 [기능] 스크랩 CRD
  mureng-api/src/main/java/net/mureng/api/member/component/MemberProfileMapper.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberProfileDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberScrapController.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyController.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyLikesController.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java
  mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java
  mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java
  mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java
  mureng-api/src/test/java/net/mureng/api/member/component/MemberProfileMapperTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberScrapControllerTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/component/TodayExpressionMapperTest.java
  mureng-api/src/test/java/net/mureng/api/todayexpression/web/TodayExpressionControllerTest.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
  mureng-core/src/main/java/net/mureng/core/member/entity/MemberScrap.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java
  mureng-core/src/main/java/net/mureng/core/todayexpression/entity/TodayExpression.java
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
Labels: application, feature

#116 [기능] 회원 이미지 업로드 기능 추가
  mureng-api/src/main/java/net/mureng/api/member/service/MemberImageService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberImageController.java
  mureng-api/src/main/java/net/mureng/api/reply/web/ReplyImageController.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberImageControllerTest.java
Labels: application, feature

#117 [보완] 질문 최대 글자수 검증 로직 추가
  mureng-api/src/main/java/net/mureng/api/question/dto/QuestionDto.java
  mureng-api/src/test/java/net/mureng/api/question/component/QuestionDtoValidationTest.java
Labels: application, enhancement, request

#119 [기능] OAuth 사용자 프로필 가져오기
  mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
Labels: application, bug, enhancement

#120 [수정] page to 0
  mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java
Labels: application, bug

#121 [수정] oauthService 수정
  mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java
  mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
Labels: application, bug

#122 [기능] 회원 정보 수정 엔드포인트 추가
  mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java
  mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberControllerTest.java
  mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
  mureng-core/src/test/resources/dbunit/expected/멤버_머렝_카운트_증가.xml
Labels: application, feature

#123 [수정] 답변 좋아요
  mureng-core/src/main/java/net/mureng/core/reply/entity/ReplyLikesPK.java
  mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java
  mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyLikesRepositoryTest.java
Labels: application, bug

#124 [기능] 사용자 성과 페이지
  mureng-api/src/main/java/net/mureng/api/badge/component/BadgeMapper.java
  mureng-api/src/main/java/net/mureng/api/badge/dto/BadgeDto.java
  mureng-api/src/main/java/net/mureng/api/member/component/MemberAchievementMapper.java
  mureng-api/src/main/java/net/mureng/api/member/component/MemberScrapMapper.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberAchievementDto.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java
  mureng-api/src/main/java/net/mureng/api/member/dto/MemberScrapDto.java
  mureng-api/src/main/java/net/mureng/api/member/service/MemberBadgeService.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberAchievementController.java
  mureng-api/src/main/java/net/mureng/api/member/web/MemberScrapController.java
  mureng-api/src/test/java/net/mureng/api/badge/BadgeMapperTest.java
  mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java
  mureng-api/src/test/java/net/mureng/api/member/component/MemberAchievementMapperTest.java
  mureng-api/src/test/java/net/mureng/api/member/component/MemberScrapMapperTest.java
  mureng-api/src/test/java/net/mureng/api/member/web/MemberAchievementControllerTest.java
  mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
  mureng-core/src/main/java/net/mureng/core/badge/entity/Badge.java
  mureng-core/src/main/java/net/mureng/core/badge/entity/BadgeAccomplished.java
  mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
Labels: application, feature

#126 [버그] 좋아요 취소 시 답변 삭제
  mureng-core/src/main/java/net/mureng/core/reply/entity/ReplyLikes.java
Labels: application, bug

#127 [수정] 테스트 실패
  mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
Labels: application, bug
